
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eankri2015
 */
public class CalculatorGUI extends javax.swing.JFrame {
    
    boolean period = false;

    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();
        setTitle("Calculator");
        //setLookAndFeel("Windows");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        Button_0 = new javax.swing.JButton();
        Button_Period = new javax.swing.JButton();
        Button_Plus = new javax.swing.JButton();
        Button_1 = new javax.swing.JButton();
        Button_2 = new javax.swing.JButton();
        Button_3 = new javax.swing.JButton();
        Button_5 = new javax.swing.JButton();
        Button_4 = new javax.swing.JButton();
        Button_6 = new javax.swing.JButton();
        Button_7 = new javax.swing.JButton();
        Button_8 = new javax.swing.JButton();
        Button_9 = new javax.swing.JButton();
        Button_BackSpace = new javax.swing.JButton();
        Button_C = new javax.swing.JButton();
        Button_CE = new javax.swing.JButton();
        Button_Multiplication = new javax.swing.JButton();
        Button_Minus = new javax.swing.JButton();
        Button_Division = new javax.swing.JButton();
        Button_PlusMinus = new javax.swing.JButton();
        Button_Equals = new javax.swing.JButton();
        Button_Percent = new javax.swing.JButton();
        Button_Reciprical = new javax.swing.JButton();
        Button_SqaureRoot = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Menu_Password = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jButton7.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 228, 241));

        display.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.setText("0");

        Button_0.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_0.setText("0");
        Button_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_0ActionPerformed(evt);
            }
        });

        Button_Period.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_Period.setText(".");
        Button_Period.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PeriodActionPerformed(evt);
            }
        });

        Button_Plus.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_Plus.setText("+");
        Button_Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PlusActionPerformed(evt);
            }
        });

        Button_1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_1.setText("1");
        Button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_1ActionPerformed(evt);
            }
        });

        Button_2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_2.setText("2");
        Button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_2ActionPerformed(evt);
            }
        });

        Button_3.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_3.setText("3");
        Button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_3ActionPerformed(evt);
            }
        });

        Button_5.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_5.setText("5");
        Button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_5ActionPerformed(evt);
            }
        });

        Button_4.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_4.setText("4");
        Button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_4ActionPerformed(evt);
            }
        });

        Button_6.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_6.setText("6");
        Button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_6ActionPerformed(evt);
            }
        });

        Button_7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_7.setText("7");
        Button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_7ActionPerformed(evt);
            }
        });

        Button_8.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_8.setText("8");
        Button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_8ActionPerformed(evt);
            }
        });

        Button_9.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_9.setText("9");
        Button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_9ActionPerformed(evt);
            }
        });

        Button_BackSpace.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_BackSpace.setText("←");
        Button_BackSpace.setBorder(null);
        Button_BackSpace.setMargin(new java.awt.Insets(2, 0, 2, 0));
        Button_BackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BackSpaceActionPerformed(evt);
            }
        });

        Button_C.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_C.setText("C");
        Button_C.setMargin(new java.awt.Insets(2, 0, 2, 0));
        Button_C.setOpaque(false);
        Button_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CActionPerformed(evt);
            }
        });

        Button_CE.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_CE.setText("CE");
        Button_CE.setBorder(null);
        Button_CE.setMargin(new java.awt.Insets(2, 0, 2, 0));
        Button_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CEActionPerformed(evt);
            }
        });

        Button_Multiplication.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_Multiplication.setText("*");
        Button_Multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MultiplicationActionPerformed(evt);
            }
        });

        Button_Minus.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_Minus.setText("-");
        Button_Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MinusActionPerformed(evt);
            }
        });

        Button_Division.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_Division.setText("/");
        Button_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DivisionActionPerformed(evt);
            }
        });

        Button_PlusMinus.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_PlusMinus.setText("±");
        Button_PlusMinus.setMargin(new java.awt.Insets(2, 0, 2, 0));
        Button_PlusMinus.setOpaque(false);
        Button_PlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PlusMinusActionPerformed(evt);
            }
        });

        Button_Equals.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_Equals.setText("=");
        Button_Equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EqualsActionPerformed(evt);
            }
        });

        Button_Percent.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_Percent.setText("%");
        Button_Percent.setMargin(new java.awt.Insets(2, 0, 2, 0));
        Button_Percent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PercentActionPerformed(evt);
            }
        });

        Button_Reciprical.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_Reciprical.setText("1/x");
        Button_Reciprical.setBorder(null);
        Button_Reciprical.setMargin(new java.awt.Insets(2, 0, 2, 0));
        Button_Reciprical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RecipricalActionPerformed(evt);
            }
        });

        Button_SqaureRoot.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Button_SqaureRoot.setText("√");
        Button_SqaureRoot.setMargin(new java.awt.Insets(2, 0, 2, 0));
        Button_SqaureRoot.setOpaque(false);
        Button_SqaureRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SqaureRootActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button_BackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_C, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_Percent, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button_PlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_SqaureRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_Multiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button_Period, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button_Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_Equals, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button_Reciprical, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_BackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_C, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_PlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_SqaureRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_Percent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Button_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_Reciprical, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_Multiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_Period, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Button_Equals, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );

        jMenu1.setText("View");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        Menu_Password.setBorder(null);
        Menu_Password.setText("Password");
        Menu_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_PasswordActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_Password);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_SqaureRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SqaureRootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_SqaureRootActionPerformed

    private void Button_RecipricalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RecipricalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_RecipricalActionPerformed

    private void Button_PercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_PercentActionPerformed

    private void Button_EqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EqualsActionPerformed
        // TODO add your handling code here:
        //pass everything into an arrayList then cycle through list
        ScriptEngineManager mgr = new ScriptEngineManager();
        ScriptEngine engine = mgr.getEngineByName("JavaScript");
        String ans = display.getText();
        try {
            display.setText(Double.toString((Double)engine.eval(ans)));
        } catch (ScriptException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_EqualsActionPerformed

    private void Button_PlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PlusMinusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_PlusMinusActionPerformed

    private void Button_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DivisionActionPerformed
        // TODO add your handling code here:
        if(display.getText().charAt(display.getText().length()-1) != '+' && 
           display.getText().charAt(display.getText().length()-1) != '-' &&
           display.getText().charAt(display.getText().length()-1) != '/' &&
           display.getText().charAt(display.getText().length()-1) != '*')
        display.setText(display.getText() + "/");
        period = false;
    }//GEN-LAST:event_Button_DivisionActionPerformed

    private void Button_MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MinusActionPerformed
        // TODO add your handling code here:
        if(display.getText().charAt(display.getText().length()-1) != '+' && 
           display.getText().charAt(display.getText().length()-1) != '-' &&
           display.getText().charAt(display.getText().length()-1) != '/' &&
           display.getText().charAt(display.getText().length()-1) != '*')
        display.setText(display.getText() + "-");
        period = false;
    }//GEN-LAST:event_Button_MinusActionPerformed

    private void Button_MultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MultiplicationActionPerformed
        // TODO add your handling code here:
        if(display.getText().charAt(display.getText().length()-1) != '+' && 
           display.getText().charAt(display.getText().length()-1) != '-' &&
           display.getText().charAt(display.getText().length()-1) != '/' &&
           display.getText().charAt(display.getText().length()-1) != '*')
        display.setText(display.getText() + "*");
        period = false;
    }//GEN-LAST:event_Button_MultiplicationActionPerformed

    private void Button_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CEActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Button_CEActionPerformed

    private void Button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_6ActionPerformed
        // TODO add your handling code here:
        add("6");
    }//GEN-LAST:event_Button_6ActionPerformed

    private void Button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_5ActionPerformed
        // TODO add your handling code here:
        add("5");
    }//GEN-LAST:event_Button_5ActionPerformed

    private void Button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_1ActionPerformed
        // TODO add your handling code here:
        add("1");
    }//GEN-LAST:event_Button_1ActionPerformed

    private void Button_PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PlusActionPerformed
        // TODO add your handling code here:
        if(display.getText().charAt(display.getText().length()-1) != '+' && 
           display.getText().charAt(display.getText().length()-1) != '-' &&
           display.getText().charAt(display.getText().length()-1) != '/' &&
           display.getText().charAt(display.getText().length()-1) != '*')
        display.setText(display.getText() + "+");
        period = false;
    }//GEN-LAST:event_Button_PlusActionPerformed

    private void Button_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_0ActionPerformed
        // TODO add your handling code here:
        add("0");
    }//GEN-LAST:event_Button_0ActionPerformed

    private void Button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_3ActionPerformed
        // TODO add your handling code here:
        add("3");
    }//GEN-LAST:event_Button_3ActionPerformed

    private void Button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_4ActionPerformed
        // TODO add your handling code here:
        add("4");
    }//GEN-LAST:event_Button_4ActionPerformed

    private void Button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_2ActionPerformed
        // TODO add your handling code here:
        add("2");
    }//GEN-LAST:event_Button_2ActionPerformed

    private void Button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_7ActionPerformed
        // TODO add your handling code here:
        add("7");
    }//GEN-LAST:event_Button_7ActionPerformed

    private void Button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_8ActionPerformed
        // TODO add your handling code here:
        add("8");
    }//GEN-LAST:event_Button_8ActionPerformed

    private void Button_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_9ActionPerformed
        // TODO add your handling code here:
        add("9");
    }//GEN-LAST:event_Button_9ActionPerformed

    private void Button_PeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PeriodActionPerformed
        // TODO add your handling code here:
        if(period == false)
        {
            display.setText(display.getText() + ".");
        }
        
        period = true;
    }//GEN-LAST:event_Button_PeriodActionPerformed

    private void Button_BackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BackSpaceActionPerformed
        // TODO add your handling code here:
        if(display.getText().length()!=0)
        {
        if(display.getText().charAt(display.getText().length()-1) == '.')
        {
            period = false;
        } 
        
        display.setText(display.getText().substring(0, display.getText().length()-1));
        }
        if(display.getText() == null || display.getText().equals("")) 
        {
            display.setText("0");
        }
        
    }//GEN-LAST:event_Button_BackSpaceActionPerformed

    private void Button_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CActionPerformed
        // TODO add your handling code here:
        display.setText("0");
        period = false;
    }//GEN-LAST:event_Button_CActionPerformed

    private void Menu_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_PasswordActionPerformed
        // TODO add your handling code here:
        String password =  JOptionPane.showInputDialog("ENTER A PASSWORD ");
        
        if(password.equals("Time is an illusion"))
        display.setText("Lunchtime, doubly so.");
    }//GEN-LAST:event_Menu_PasswordActionPerformed

    public void add(String character)
    { 
        if(display.getText().equals("0"))
        {
            display.setText(character);
        }
        
        else
        {
            display.setText(display.getText() + character);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_0;
    private javax.swing.JButton Button_1;
    private javax.swing.JButton Button_2;
    private javax.swing.JButton Button_3;
    private javax.swing.JButton Button_4;
    private javax.swing.JButton Button_5;
    private javax.swing.JButton Button_6;
    private javax.swing.JButton Button_7;
    private javax.swing.JButton Button_8;
    private javax.swing.JButton Button_9;
    private javax.swing.JButton Button_BackSpace;
    private javax.swing.JButton Button_C;
    private javax.swing.JButton Button_CE;
    private javax.swing.JButton Button_Division;
    private javax.swing.JButton Button_Equals;
    private javax.swing.JButton Button_Minus;
    private javax.swing.JButton Button_Multiplication;
    private javax.swing.JButton Button_Percent;
    private javax.swing.JButton Button_Period;
    private javax.swing.JButton Button_Plus;
    private javax.swing.JButton Button_PlusMinus;
    private javax.swing.JButton Button_Reciprical;
    private javax.swing.JButton Button_SqaureRoot;
    private javax.swing.JMenu Menu_Password;
    private javax.swing.JTextField display;
    private javax.swing.JButton jButton7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
